apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-falsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-falsa
  template:
    metadata:
      labels:
        app: api-falsa
    spec:
      containers:
        - name: api-falsa
          image: api-falsa:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-falsa
spec:
  selector:
    app: api-falsa
  ports:
    - port: 5000
