# Usar imagen oficial de Python
FROM python:3.11-slim

# Crear directorio de trabajo
WORKDIR /app

# Copiar archivos
COPY encuestas.py .

# Instalar dependencias
RUN pip install Flask

# Exponer el puerto
EXPOSE 5000

# Comando para ejecutar la API
CMD ["python", "encuestas.py"]
